version: '2.29.2'

services:
  app:
    build: 
      args:
        user: rafael
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-relacionamentos/app_laravel_relacionamentos
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    restart: always
    depends_on:
      - redis
      - queue
    networks:
      - laravel-relacionamentos

  # nginx
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 83:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel-relacionamentos
    
  # redis
  redis:
    image: redis:latest
    networks:
      - laravel-relacionamentos

  # queue:
  queue:
    build: 
      args:
        user: rafael
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    restart: always
    command: "php artisan queue:work"
    volumes:
      - ./:/var/www
    depends_on:
      - redis
    networks:
      - laravel-relacionamentos

  # mysql
  mysql:
    image: mysql:5.7.22
    restart: always
    ports:
      - 3309:3306 
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel-relacionamentos

networks:
  laravel-relacionamentos:
    driver: bridge